### ISSUE TITLE
Weather : 모델 클레스 선정

### ISSUE THREAD

**Issue by BAUu** [BAUu/weather_teamB1#1]
- 온도
- 날씨
- 지역
- 최대 온도
- 최저 온도

**Comment by jiwonHub** [comment]
일주일 간 일 별 
+ 최대 강수량
+ 최대 온도
+ 최저 온도
+ 최대 체감 온도
+ 최저 체감 온도
+ 날씨 코드(아이콘)

**Comment by BAUu** [comment]
![Image](https://github.com/BAUu/weather_teamB1/assets/44741680/e3f738c4-d697-44a7-abf2-cdc830540b98)

**Comment by BAUu** [comment]
![image](https://github.com/BAUu/weather_teamB1/assets/44741680/a15bceee-b13e-47fa-803c-4c664a702836)
